version: "3.8"

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    restart: always
    ports:
      - "5000:5000"
    environment:
      env_file: ./system_configs/.env
    volumes:
      - ./:/app
